# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sensor.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'sensor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csensor.proto\":\n\x08Metadata\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x01(\r\x12\x11\n\tlogger_id\x18\x02 \x01(\r\x12\n\n\x02ts\x18\x03 \x01(\r\"~\n\x15\x46ullSensorMeasurement\x12\x16\n\x0cunsigned_int\x18\x01 \x01(\x04H\x00\x12\x14\n\nsigned_int\x18\x02 \x01(\x12H\x00\x12\x18\n\x0e\x66loating_point\x18\x03 \x01(\x01H\x00\x12\x0e\n\x04text\x18\x04 \x01(\tH\x00\x42\r\n\x0bmeasurement\"Q\n\x16\x44\x65ltaSensorMeasurement\x12\x14\n\nsigned_int\x18\x01 \x01(\x12H\x00\x12\x18\n\x0e\x66loating_point\x18\x02 \x01(\x01H\x00\x42\x07\n\x05\x64\x65lta\"\xa8\x01\n\x11SensorMeasurement\x12\x17\n\x04meta\x18\x01 \x01(\x0b\x32\t.Metadata\x12\x19\n\x04type\x18\x02 \x01(\x0e\x32\x0b.SensorType\x12&\n\x04\x66ull\x18\x03 \x01(\x0b\x32\x16.FullSensorMeasurementH\x00\x12(\n\x05\x64\x65lta\x18\x04 \x01(\x0b\x32\x17.DeltaSensorMeasurementH\x00\x42\r\n\x0bmeasurement\"_\n\x1aRepeatedSensorMeasurements\x12\x17\n\x04meta\x18\x01 \x01(\x0b\x32\t.Metadata\x12(\n\x0cmeasurements\x18\x02 \x03(\x0b\x32\x12.SensorMeasurement*\xd1\x01\n\nSensorType\x12\x11\n\rPOWER_VOLTAGE\x10\x00\x12\x11\n\rPOWER_CURRENT\x10\x01\x12\x0f\n\x0bTEROS12_VWC\x10\x02\x12\x10\n\x0cTEROS12_TEMP\x10\x03\x12\x0e\n\nTEROS12_EC\x10\x04\x12\x14\n\x10PHYTOS31_VOLTAGE\x10\x05\x12\x19\n\x15PHYTOS31_LEAF_WETNESS\x10\x06\x12\x13\n\x0f\x42ME280_PRESSURE\x10\x07\x12\x0f\n\x0b\x42ME280_TEMP\x10\x08\x12\x13\n\x0f\x42ME280_HUMIDITY\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sensor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENSORTYPE']._serialized_start=556
  _globals['_SENSORTYPE']._serialized_end=765
  _globals['_METADATA']._serialized_start=16
  _globals['_METADATA']._serialized_end=74
  _globals['_FULLSENSORMEASUREMENT']._serialized_start=76
  _globals['_FULLSENSORMEASUREMENT']._serialized_end=202
  _globals['_DELTASENSORMEASUREMENT']._serialized_start=204
  _globals['_DELTASENSORMEASUREMENT']._serialized_end=285
  _globals['_SENSORMEASUREMENT']._serialized_start=288
  _globals['_SENSORMEASUREMENT']._serialized_end=456
  _globals['_REPEATEDSENSORMEASUREMENTS']._serialized_start=458
  _globals['_REPEATEDSENSORMEASUREMENTS']._serialized_end=553
# @@protoc_insertion_point(module_scope)
